# Generated by Django 3.0.5 on 2022-07-11 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxano', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partnership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=192)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=192)),
                ('money', models.IntegerField()),
            ],
        ),
    ]
