# Generated by Django 3.0.5 on 2022-07-11 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxano', '0003_partnership'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnership',
            name='subject',
        ),
        migrations.AddField(
            model_name='partnership',
            name='location',
            field=models.CharField(default='null', max_length=30),
        ),
    ]
