# Generated by Django 3.0.5 on 2022-07-11 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auxano', '0004_auto_20220711_1410'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partnership',
            old_name='money',
            new_name='donation',
        ),
    ]
