# Generated by Django 3.0.5 on 2022-07-11 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxano', '0005_auto_20220711_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(default='08000000000', max_length=12),
        ),
        migrations.AddField(
            model_name='partnership',
            name='phone_number',
            field=models.CharField(default='08000000000', max_length=12),
        ),
    ]
